Вёрстка адаптивных сетки. попытка первая
htmlacademy-adaptive/1422099-pink-20 pull request #6
Opened 2020-08-27 12:03 UTC by msuhaka

Головоломка ещё та... Трудно идёт, но надеюсь в правильном направлении.

2020-08-27 20:16 UTC, raccoonroman requested changes

2020-08-27 20:16 UTC, raccoonroman commented on source/less/blocks/download.less
> +  height: 271px;
не нужно ограничивать высоту, верстка не пройдет тест на переполнение контентом

2020-08-27 20:16 UTC, raccoonroman commented on source/less/blocks/download.less
> +    font-size: 18;
```suggestion
    font-size: 18px;
```

2020-08-27 20:16 UTC, raccoonroman commented on source/less/blocks/download.less
> +  position: absolute;
зачем их делать абсолютом?

2020-08-27 20:16 UTC, raccoonroman commented on source/less/blocks/download.less
> +    background-repeat: no-repeat;
общие стили задай базовому классу, а в модификатор пиши только то, что отличается от других модификаторов

2020-08-27 20:16 UTC, raccoonroman commented on source/less/style.less
> +@import "blocks/page-main.less";
убери разширение файла

2020-08-27 20:16 UTC, raccoonroman commented on source/less/blocks/page-main.less
> +  min-width: 320px;
пропиши это свойство для body и больше нигде не используй

2020-08-27 20:16 UTC, raccoonroman commented on source/less/blocks/social.less
> +  position: absolute;
ссылку не нужно делать абсолютом

2020-08-27 20:16 UTC, raccoonroman commented on source/less/blocks/social.less
> +  position: absolute;
кликабельным должен быть весь кружок https://prnt.sc/u730um для удобства пользователя

2020-08-27 20:16 UTC, raccoonroman commented on source/less/blocks/headline.less
> +  height: 170px;
не нужно ограничивать высоту, верстка не пройдет тест на переполнение контентом

2020-08-27 20:16 UTC, raccoonroman commented on source/less/blocks/page-header.less
> +      display: none;
если для таблеток стоит display: none;, то для десктопов уже прописывать не надо

2020-08-29 15:17 UTC, msuhaka commented on source/form.html
> +                >
да, это редактор такое творит

2020-08-29 15:18 UTC, msuhaka commented on source/form.html
> +                >
исправлено

2020-08-29 15:18 UTC, msuhaka commented on source/form.html
> +          Конкурс на самое безбашенное <br>путешествие с Пинк
исправлено

2020-08-29 17:14 UTC, msuhaka commented on source/form.html
> +                  <g>
исправлено

2020-08-29 17:14 UTC, msuhaka commented on source/form.html
> +              <svg id="fb-link" width="9" height="19" fill="#d22856">
исправлено

2020-08-29 17:14 UTC, msuhaka commented on source/less/style.less
> +@import "blocks/page-main.less";
Прости, пропустил... Исправлено

2020-08-29 17:16 UTC, msuhaka commented on source/less/blocks/page-main.less
> +  min-width: 320px;
исправлено

2020-08-29 17:39 UTC, msuhaka commented on source/less/blocks/social.less
> +  position: absolute;
исправлено

2020-08-29 17:42 UTC, msuhaka commented on source/less/blocks/headline.less
> +  height: 170px;
Разве в демонстрации не делали так ? 
![image](https://user-images.githubusercontent.com/65132275/91642989-d3714600-ea2f-11ea-9ed5-ede80e3729e9.png)

2020-08-29 17:43 UTC, msuhaka commented on source/less/blocks/headline.less
> +  height: 170px;
в принципе, я помню про этот критерий, но подумал что в адаптивной вёрстке он снимается..

2020-08-29 17:45 UTC, msuhaka commented on source/less/blocks/page-header.less
> +      display: none;
исправлено

2020-08-29 17:50 UTC, msuhaka commented on source/less/blocks/page-header.less
> +      display: none;
вернул обратно, потому что логотип из дескопной всё таки отображался

2020-08-29 17:57 UTC, msuhaka commented on source/less/blocks/benefits.less
> +    background: url("/img/iphone-screen-mobile@1x.png");
У меня она почему-то отображаются... Вообще-то, с этими картинками у меня сплошная свистопляска. Прописываю путь, и они то есть то их их нет... Загадочные дела! 
url ("/img/image.jpg") = url ("..img/image.jpg") ??

2020-08-29 18:05 UTC, msuhaka commented on source/less/blocks/benefits.less
> +    background: url("/img/iphone-screen-mobile@1x.png");
![image](https://user-images.githubusercontent.com/65132275/91643360-ef2a1b80-ea32-11ea-82fe-3ab03084f3af.png)

2020-08-29 18:08 UTC, msuhaka commented on source/less/blocks/benefits.less
> +      left: 50px;
так не выравнивается. Я сделал 
      ```
transform: translateX(-50%);
      left: 25%; 
```

2020-08-31 13:12 UTC, msuhaka commented on source/less/blocks/benefits.less
> +  height: 900px;
исправлено

2020-08-31 13:13 UTC, msuhaka commented on source/less/blocks/benefits.less
> +    background: url("/img/iphone-screen-mobile@1x.png");
я убрал `position: absolute` и консоль ошибок больше не выдаёт. Должны по идее показываться.

2020-08-31 13:15 UTC, msuhaka commented on source/less/blocks/benefits.less
> +        background: url("/img/iphone-screen-1-desktop@1x.png");
я убрал position: absolute и консоль ошибок больше не выдаёт. Должны по идее показываться.

Исправлено??

2020-08-31 13:16 UTC, msuhaka commented on source/less/blocks/download.less
> +  height: 666px;
исправлено

2020-08-31 15:03 UTC, msuhaka commented on source/less/blocks/download.less
> +      position: absolute;
исправлено

2020-08-31 15:03 UTC, msuhaka commented on source/less/blocks/download.less
> +  height: 271px;
исправлено

2020-08-31 15:05 UTC, msuhaka commented on source/less/blocks/download.less
> +    font-size: 18;
исправлено

2020-08-31 15:06 UTC, msuhaka commented on source/less/blocks/download.less
> +  position: absolute;
исправлено

2020-08-31 15:08 UTC, msuhaka commented on source/less/blocks/download.less
> +    background-repeat: no-repeat;
исправлено

2020-08-31 15:36 UTC, msuhaka commented on source/less/blocks/benefits.less
> +        left: 65px;
исправлено

2020-08-31 17:13 UTC, msuhaka commented on source/less/blocks/benefits.less
> +      left: 50px;
исправлено

2020-08-31 18:39 UTC, raccoonroman commented on source/less/blocks/headline.less
> +  height: 170px;
в демке там нет текста, потому можно задать фикс высоту

2020-08-31 20:14 UTC, raccoonroman commented on source/less/blocks/benefits.less
> +    background: url("/img/iphone-screen-mobile@1x.png");
Вот сколько не подключенных картинок https://prnt.sc/u96yql

2020-08-31 20:14 UTC, raccoonroman commented on source/less/blocks/main-nav.less
> +  @media (min-width: @desktop-width) {
используй миксин

2020-08-31 20:15 UTC, merged